<Project>

  <Import Project="version.props" />

  <PropertyGroup>
    <Authors>Jeremy Morren</Authors>
    <Copyright>Copyright © Jeremy Morren</Copyright>
    <NeutralLanguage>en-GB</NeutralLanguage>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>

    <LangVersion>12</LangVersion>
  </PropertyGroup>

    <!-- Deterministic builds for everyone -->
  <PropertyGroup>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  
  <PropertyGroup>
    <DebugType>embedded</DebugType>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageOutputPath>$(MSBuildThisFileDirectory)\artifacts</PackageOutputPath>
    
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>