using System.Reflection;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace WinDataBinding.SourceGenerator.Internal;

/// <summary>Writes the generated source for one <see cref="BinderModel"/>.</summary>
internal static class Emitter
{
    private const string Comparer = "global::System.Collections.Generic.IEqualityComparer";

    private static readonly string ToolName = typeof(Emitter).Assembly.GetName().Name!;
    private static readonly string ToolVersion = typeof(Emitter).Assembly.GetName().Version!.ToString();

    /// <summary>
    /// Doc-comment warnings the generated file suppresses. 
    /// 
    /// A cref names a type the consuming project may not see from here, 
    /// and the comments sit outside the <c>#if</c> guarding a per-framework property; 
    /// neither is a real problem. One list drives both the comments and the pragma, so they cannot drift apart.
    /// 
    /// CS1587: our complicated if defs for per-framework properties confuse the analyzer (but not the compiler),
    /// so we can suppress it.
    /// </summary>
    private static readonly (string Code, string Reason)[] SuppressedWarnings =
    [
        ("CS1574", "XML comment has a cref attribute that could not be resolved"),
        ("CS1584", "XML comment has a syntactically incorrect cref attribute"),
        ("CS1581", "Invalid return type in XML comment cref attribute"),
        ("CS1580", "Invalid type for parameter in XML comment cref attribute"),
        ("CS1587", "XML comment is not placed on a valid language element"),
    ];

    public static void Emit(SourceProductionContext context, BinderModel model)
    {
        foreach (var diagnostic in model.Diagnostics)
            context.ReportDiagnostic(diagnostic.ToDiagnostic());

        // Emitting on top of an error (a non-partial class, a generic type) only adds noise.
        if (model.Diagnostics.Any(d => d.Descriptor.DefaultSeverity == DiagnosticSeverity.Error))
            return;

        context.AddSource(model.HintName, SourceText.From(Write(model), Encoding.UTF8));
    }

    private static string Write(BinderModel model)
    {
        // Roughly 400 characters per property, plus the file header and class shell.
        var writer = new Writer(512 + model.Properties.Count * 400);

        writer.Line("// <auto-generated>");
        writer.Line("//     This file was generated by " + ToolName + ".");
        writer.Line("//     Changes to this file will be lost if the code is regenerated.");
        writer.Line("// </auto-generated>");
        writer.Line("// ReSharper disable all");

        foreach (var (code, reason) in SuppressedWarnings)
            writer.Line($"// {code} {reason}: https://learn.microsoft.com/dotnet/csharp/misc/{code.ToLowerInvariant()}");

        writer.Line("#pragma warning disable " + string.Join(", ", SuppressedWarnings.Select(w => w.Code)));
        writer.Line("#nullable enable annotations");
        writer.Line("#nullable disable warnings");
        writer.Line();

        if (model.Namespace is not null)
        {
            writer.Line("namespace " + model.Namespace);
            writer.OpenBrace();
        }

        foreach (var containing in model.ContainingTypes)
        {
            writer.Line("partial " + containing);
            writer.OpenBrace();
        }

        writer.Line($"[global::System.CodeDom.Compiler.GeneratedCode(\"{ToolName}\", \"{ToolVersion}\")]");

        // A readonly struct is free of the defensive copies an ordinary one would take on every member read.
        var declaration = model.Keyword == "struct" ? "readonly partial struct" : $"partial {model.Keyword}";

        var interfaces = new List<string>
        {
            $"global::System.IEquatable<{model.ClassName}>",
            $"{Comparer}<{model.SourceType}>",
        };
        if (model.SourceIsComparable) interfaces.Add($"global::System.IComparable<{model.ClassName}>");

        writer.Line($"{declaration} {model.ClassName} : {string.Join(", ", interfaces)}");
        writer.OpenBrace();

        writer.Line($"private readonly {model.SourceType} _source;");
        writer.Line();
        writer.Line($"{model.CtorAccessibility} {model.ClassName}({model.SourceType} source)");
        writer.OpenBrace();
        writer.Raw("#if NET6_0_OR_GREATER");
        writer.Line("global::System.ArgumentNullException.ThrowIfNull(source);");
        writer.Line("_source = source;");
        writer.Raw("#else");
        writer.Line("_source = source ?? throw new global::System.ArgumentNullException(nameof(source));");
        writer.Raw("#endif");
        writer.CloseBrace();

        WriteFactory(writer, model);
        WriteEquality(writer, model);
        WriteComparer(writer, model);
        WriteComparable(writer, model);

        foreach (var property in model.Properties)
        {
            writer.Line();
            WriteProperty(writer, property);
        }

        writer.CloseBrace();

        for (var i = 0; i < model.ContainingTypes.Count; i++) writer.CloseBrace();
        if (model.Namespace is not null) writer.CloseBrace();

        return writer.ToString();
    }

    /// <summary>
    /// A factory that maps a null source to a null binder. 
    /// A struct cannot express that through its constructor at all, and for a class it saves the caller a null check either way.
    /// </summary>
    private static void WriteFactory(Writer writer, BinderModel model)
    {
        writer.Line();
        writer.Line($"/// <summary>Wraps <paramref name=\"source\"/>, or returns null when it is null.</summary>");

        if (model.ContractAnnotation)
            writer.Line("[global::JetBrains.Annotations.ContractAnnotation(\"null => null; notnull => notnull\")]");

        if (model.NotNullIfNotNull)
            writer.Line("[return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(\"source\")]");

        writer.Line($"{model.CtorAccessibility} static {model.ClassName}? Create({model.SourceType}? source) =>");
        writer.Line($"    source is not null ? new {model.ClassName}(source) : null;");
    }

    /// <summary>
    /// Equality between binders, which is equality between the sources they wrap. 
    /// The object overrides come with it: without them a struct binder would fall back to ValueType.Equals, 
    /// which compares a struct holding a reference field by reflection, and the two notions of equality could disagree.
    /// </summary>
    private static void WriteEquality(Writer writer, BinderModel model)
    {
        var equality = $"global::System.Collections.Generic.EqualityComparer<{model.SourceType}>.Default";
        var other = model.Keyword == "struct" ? model.ClassName : model.ClassName + "?";
        var guard = model.Keyword == "struct" ? "" : "other is not null && ";

        writer.Line();
        writer.Line("/// <summary>Compares this binder to another for equality.</summary>");
        writer.Line("/// <remarks>Two binders are equal when the sources they wrap are.</remarks>");
        writer.Line($"public bool Equals({other} other) =>");
        writer.Line($"    {guard}{equality}.Equals(_source, other._source);");

        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line($"public override bool Equals(object? obj) => obj is {model.ClassName} other && Equals(other);");

        writer.Line();
        writer.Line("/// <inheritdoc/>");

        // A default struct binder has no source at all, and the default comparer will not hash null.
        var hash = model.SourceIsReference
            ? $"_source is null ? 0 : {equality}.GetHashCode(_source)"
            : $"{equality}.GetHashCode(_source)";

        writer.Line($"public override int GetHashCode() => {hash};");
    }

    /// <summary>
    /// Comparison of two sources, handed straight to the default comparer for the type.
    /// </summary>
    private static void WriteComparer(Writer writer, BinderModel model)
    {
        var source = model.SourceType;
        var nullable = model.SourceIsReference ? source + "?" : source;
        var equality = $"global::System.Collections.Generic.EqualityComparer<{source}>.Default";

        // Implemented explicitly. 
        // A public method taking the source type would not compile when the source is less accessible than the binder,
        // and Equals(TSource, TSource) beside object.Equals invites being called by mistake.
        var self = $"{Comparer}<{source}>";

        writer.Line();
        writer.Line("/// <summary>Compares two sources with the default comparer for their type.</summary>");
        writer.Line($"bool {self}.Equals({nullable} x, {nullable} y) => {equality}.Equals(x, y);");

        writer.Line();
        writer.Line("/// <summary>Hashes a source with the default comparer for its type.</summary>");
        writer.Line($"int {self}.GetHashCode({source} obj) => {equality}.GetHashCode(obj);");
    }

    /// <summary>Ordering, mirrored from the source: a binder sorts however the thing it wraps sorts.</summary>
    private static void WriteComparable(Writer writer, BinderModel model)
    {
        if (!model.SourceIsComparable) return;

        var ordering = $"global::System.Collections.Generic.Comparer<{model.SourceType}>.Default";

        writer.Line();
        writer.Line("/// <summary>Orders by the source, using the default comparer for its type.</summary>");

        if (model.Keyword == "struct")
        {
            writer.Line($"public int CompareTo({model.ClassName} other) =>");
            writer.Line($"    {ordering}.Compare(_source, other._source);");
        }
        else
        {
            // Sorting a list of binders puts the nulls first, as the default comparer would.
            writer.Line($"public int CompareTo({model.ClassName}? other) =>");
            writer.Line($"    other is null ? 1 : {ordering}.Compare(_source, other._source);");
        }
    }

    private static void WriteProperty(Writer writer, GeneratedProperty property)
    {
        // Only the summary and the property itself vary by target framework; remarks and description do not.
        if (property.TypePre6 is null)
        {
            writer.Line($"/// <summary><c>{Xml(property.Summary)}</c></summary>");
        }
        else
        {
            writer.Raw("#if NET6_0_OR_GREATER");
            writer.Line($"/// <summary><c>{Xml(property.Summary)}</c></summary>");
            writer.Raw("#else");
            writer.Line($"/// <summary><c>{Xml(property.SummaryPre6!)}</c></summary>");
            writer.Raw("#endif");
        }

        var remarks = new StringBuilder("/// <remarks>", 24 + property.Remarks.Count * 48);
        for (var i = 0; i < property.Remarks.Count; i++)
        {
            if (i > 0) remarks.Append(' ');
            remarks.Append("<see cref=\"").Append(property.Remarks[i]).Append("\"/>");
        }
        writer.Line(remarks.Append("</remarks>").ToString());

        if (property.Description is not null)
            writer.Line($"[global::System.ComponentModel.Description({SymbolDisplay.FormatLiteral(property.Description, quote: true)})]");

        if (property.TypePre6 is null)
        {
            writer.Line($"public {property.Type} {property.Name} => {property.Expression};");
        }
        else
        {
            writer.Raw("#if NET6_0_OR_GREATER");
            writer.Line($"public {property.Type} {property.Name} => {property.Expression};");
            writer.Raw("#else");
            writer.Line($"public {property.TypePre6} {property.Name} => {property.ExpressionPre6};");
            writer.Raw("#endif");
        }
    }

    /// <summary>
    /// Escapes text destined for an XML doc comment. 
    /// Guarded expressions contain '&amp;&amp;', and rendered sequences contain quotes, which are legal unescaped in element content.
    /// </summary>
    private static string Xml(string text) => new XText(text).ToString();

    /// <summary>A minimal indenting writer; building source with SyntaxNodes is far slower.</summary>
    private sealed class Writer(int capacity)
    {
        private readonly StringBuilder _builder = new(capacity);
        private int _indent;

        public void Line(string text = "")
        {
            if (text.Length > 0) _builder.Append(' ', _indent * 4).Append(text);
            _builder.AppendLine();
        }

        /// <summary>Writes at column zero, for preprocessor directives.</summary>
        public void Raw(string text) => _builder.AppendLine(text);

        public void OpenBrace()
        {
            Line("{");
            _indent++;
        }

        public void CloseBrace()
        {
            _indent--;
            Line("}");
        }

        public override string ToString() => _builder.ToString();
    }
}
