using System.Reflection;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace WinDataBinding.SourceGenerator.Internal;

/// <summary>Writes the generated source for one <see cref="BinderModel"/>.</summary>
internal static class Emitter
{
    private static readonly string ToolName = typeof(Emitter).Assembly.GetName().Name!;
    private static readonly string ToolVersion = typeof(Emitter).Assembly.GetName().Version!.ToString();

    public static void Emit(SourceProductionContext context, BinderModel model)
    {
        foreach (var diagnostic in model.Diagnostics)
            context.ReportDiagnostic(diagnostic.ToDiagnostic());

        // Emitting on top of an error (a non-partial class, a generic type) only adds noise.
        if (model.Diagnostics.Any(d => d.Descriptor.DefaultSeverity == DiagnosticSeverity.Error))
            return;

        context.AddSource(model.HintName, SourceText.From(Write(model), Encoding.UTF8));
    }

    private static string Write(BinderModel model)
    {
        // Roughly 400 characters per property, plus the file header and class shell.
        var writer = new Writer(512 + model.Properties.Count * 400);

        writer.Line("// <auto-generated>");
        writer.Line("//     This file was generated by " + ToolName + ".");
        writer.Line("//     Changes to this file will be lost if the code is regenerated.");
        writer.Line("// </auto-generated>");
        writer.Line("// ReSharper disable all");
        writer.Line("#nullable enable annotations");
        writer.Line("#nullable disable warnings");
        writer.Line();

        if (model.Namespace is not null)
        {
            writer.Line("namespace " + model.Namespace);
            writer.OpenBrace();
        }

        foreach (var containing in model.ContainingTypes)
        {
            writer.Line("partial class " + containing);
            writer.OpenBrace();
        }

        writer.Line($"[global::System.CodeDom.Compiler.GeneratedCode(\"{ToolName}\", \"{ToolVersion}\")]");
        writer.Line("partial class " + model.ClassName);
        writer.OpenBrace();

        writer.Line($"private readonly {model.SourceType} _source;");
        writer.Line();
        writer.Line($"{model.CtorAccessibility} {model.ClassName}({model.SourceType} source)");
        writer.OpenBrace();
        writer.Raw("#if NET6_0_OR_GREATER");
        writer.Line("global::System.ArgumentNullException.ThrowIfNull(source);");
        writer.Line("_source = source;");
        writer.Raw("#else");
        writer.Line("_source = source ?? throw new global::System.ArgumentNullException(nameof(source));");
        writer.Raw("#endif");
        writer.CloseBrace();

        foreach (var property in model.Properties)
        {
            writer.Line();
            WriteProperty(writer, property);
        }

        writer.CloseBrace();

        for (var i = 0; i < model.ContainingTypes.Count; i++) writer.CloseBrace();
        if (model.Namespace is not null) writer.CloseBrace();

        return writer.ToString();
    }

    private static void WriteProperty(Writer writer, GeneratedProperty property)
    {
        // Only the summary and the property itself vary by target framework; remarks and description do not.
        if (property.TypePre6 is null)
        {
            writer.Line($"/// <summary><c>{Xml(property.Summary)}</c></summary>");
        }
        else
        {
            writer.Raw("#if NET6_0_OR_GREATER");
            writer.Line($"/// <summary><c>{Xml(property.Summary)}</c></summary>");
            writer.Raw("#else");
            writer.Line($"/// <summary><c>{Xml(property.SummaryPre6!)}</c></summary>");
            writer.Raw("#endif");
        }

        var remarks = new StringBuilder("/// <remarks>", 24 + property.Remarks.Count * 48);
        for (var i = 0; i < property.Remarks.Count; i++)
        {
            if (i > 0) remarks.Append(' ');
            remarks.Append("<see cref=\"").Append(property.Remarks[i]).Append("\"/>");
        }
        writer.Line(remarks.Append("</remarks>").ToString());

        if (property.Description is not null)
            writer.Line($"[global::System.ComponentModel.Description({SymbolDisplay.FormatLiteral(property.Description, quote: true)})]");

        if (property.TypePre6 is null)
        {
            writer.Line($"public {property.Type} {property.Name} => {property.Expression};");
        }
        else
        {
            writer.Raw("#if NET6_0_OR_GREATER");
            writer.Line($"public {property.Type} {property.Name} => {property.Expression};");
            writer.Raw("#else");
            writer.Line($"public {property.TypePre6} {property.Name} => {property.ExpressionPre6};");
            writer.Raw("#endif");
        }
    }

    /// <summary>
    /// Escapes text destined for an XML doc comment. Guarded expressions contain '&amp;&amp;', and rendered
    /// sequences contain quotes, which are legal unescaped in element content.
    /// </summary>
    private static string Xml(string text) => new XText(text).ToString();

    /// <summary>A minimal indenting writer; building source with SyntaxNodes is far slower.</summary>
    private sealed class Writer(int capacity)
    {
        private readonly StringBuilder _builder = new(capacity);
        private int _indent;

        public void Line(string text = "")
        {
            if (text.Length > 0) _builder.Append(' ', _indent * 4).Append(text);
            _builder.AppendLine();
        }

        /// <summary>Writes at column zero, for preprocessor directives.</summary>
        public void Raw(string text) => _builder.AppendLine(text);

        public void OpenBrace()
        {
            Line("{");
            _indent++;
        }

        public void CloseBrace()
        {
            _indent--;
            Line("}");
        }

        public override string ToString() => _builder.ToString();
    }
}
